dtb-$(CONFIG_ARCH_MXC) += myd-lmx9x-11x11.dtb \
			  myd-lmx9x-11x11-hdmi.dtb \
			  myd-lmx9x-11x11-rgb.dtb \
			  myd-lmx9x-11x11-lvds.dtb
# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += myd-jmx95-15x15.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-jmx95-15x15-root.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-jmx95-15x15-lt9611-lvds1-ov5640.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-jmx95-15x15-4k-lt9611-lvds1-ov5640.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-jmx95-15x15-lvds0-lvds1-ov5640.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-jmx95-15x15-dsi-mipi101c.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-jmx95-15x15-lvds-dual.dtb

dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-lvds1.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-lvds-dual.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-dsi.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-csi1-ov5640.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-hdmi-ov13855-isp.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-2g.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-dsi-2g.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-lvds1-2g.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-lvds-dual-2g.dtb
dtb-$(CONFIG_ARCH_MXC) += myd-js8mpq-csi1-ov5640-2g.dtb
