dtb-$(CONFIG_ARCH_MYS_IMX91) += mys-imx91-11x11.dtb \
			        mys-imx91-11x11-mqs.dtb \
					mys-imx91-11x11-tianma-wvga-panel.dtb \
					mys-imx91-11x11-fec.dtb \

dtb-$(CONFIG_ARCH_MYD_IMX91) += myd-imx91-11x11.dtb \
				myd-imx91-11x11-RGB.dtb \
