# SPDX-License-Identifier: GPL-2.0

# required for overlay support

dtb-$(CONFIG_ARCH_MXC) +=  myb-imx8mm-base.dtb \
	                   myb-imx8mm-lcd-atk-10-1.dtb \
			   myb-imx8mm-rpmsg-m4.dtb \
			   myb-imx8mm-lcd-me190etn01.dtb \
			   myb-imx8mm-lcd-hontron-7.dtb \
			   mys-imx8mm-evk-rpmsg.dtb \
			   mys-imx8mm-lt8912-atk-10-1.dtb \
			   mys-imx8mm-lt8912-hontron-7.dtb
